spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mos_burgers?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

cloudinary:
  cloud_name: dfqoxdaux
  api_key: 541251548876181
  api_secret: fWLiAcjor22gHLzoS_2zJrbj-yA



